### ISSUE TITLE
Support for dependency injection

### ISSUE THREAD

**Issue by mchaloupka** [fsprojects/TickSpec#1]
Usage of dependency injection to create instances will help to resolve more complicated dependencies. Moreover, it enables proper usage of IDisposable classes.

@michalkovy has already a working version using BoDi (DI used in SpecFlow). It would be nice to get it into the official tickspec nuget release. If you will agree, we can create pull request with the feature.

**Comment by bartelink** [comment]
Hi - feel free to @ me in next time - I'm am marooned on a non-github workflow platform so I'm not maniacally pressing `g`,`n` every two minutes like in those happy times.

I believe I may have put this in a discussion on codeplex back in the day myself as it's definitely immensely valuable as it allows one to separate stuff out properly (and Disposable resources are common in acceptance tests IME)

IIRC there's an `IServiceProvider` in there that just needs to be surfaced?

Key considerations are:
- not adding much code / complexity / dependencies
- I personally would want it to play well with xUnit 2 so would be reviewing from that angle and/or adjusting samples to demo how your solution also works nearly in that context
- ideally playing with another execution context or two besides that (i.e. if your PR is not xUnit only, that's ideal)

cc @ptrelford any thoughts/considerations you can think of ?

**Comment by mchaloupka** [comment]
@bartelink I agree with you. I was thinking about adding a dependency to some standard DI. However, it seems to me that it is quite easy to have a very simple DI support without any dependency. See the pull request.

**Comment by pmbanka** [comment]
@bartelink 

Sorry for writing on a closed issue, but I just wanted to ask about this code being released on NuGet. I have a need to pass xUnit's `ITestOutputHelper` to my TickSpec tests, and `IServiceProvider` seems to be the only option here, but the latest package on NuGet doesn't have this PR included. Are there any plans to release it soon? :)

**Comment by bartelink** [comment]
@pmbanka Passing `ITestOutputHelper` sounds like an ideal use for the facility (but be warned that xUnit does not wire that through to VS2017 atm (which I think is VS' fault)).

Getting a NuGet out is a 'simple' matter of running the script to gen and publish. @ptrelford and I have NuGet publish rights, but I unfortunately have no familiarity with the process and no time right now; if this changes I'll post here when it happens. 

Until the publish happens, the best I can unfortunately offer is the suggestion that a get of this repo's `master and a `./build` will generate a correct DLL with the facility in place as intended.

**Comment by pmbanka** [comment]
@bartelink thanks for the answer! Yeah I'll use the dll built from the repo :) 

Thank you for maintaining this library!
