### ISSUE TITLE
The nuget is outdated

### ISSUE THREAD

**Issue by cboudereau** [fsprojects/TickSpec#14]
The nuget indicate a version from 2014 and some features like "functional style without mutable" doesn't work with error message : 
"Step methods must return void/unit on line 5 in Feature: Refunded or replaced items should be returned to stock
	"And I have 3 black jumpers left in stock"

Note that this sample works well on the sample part.

I guess that the nuget hasn't be pushed.

Could you push the new version ?

Thanks!

**Comment by sergey-tihon** [comment]
@bartelink could we publish from `master` to fresh `NuGet`?

**Comment by bartelink** [comment]
@sergey-tihon yes, it should be shipshape; feel free to do so; all that's missing is me knowing the script to run to push (I have another project that I owe a packaging script and actual open sourcing to first in the queue!)

**Comment by sergey-tihon** [comment]
@bartelink could you please increment version and publish?
I cannot compile project locally, I could only get the latest package from AppVeyor and upload to NuGet manually

**Comment by bartelink** [comment]
I have a commit there making it v1.1 and updating `paket.bootstrapper.exe` but don't know how to sync that into appveyor (which is on 1.0.1.140) and have manually uploaded the nupkg. Next time I definitely don't want do be doing a manual build ;) @cboudereau please let us know how you fare and/or encounter any issues

**Comment by sergey-tihon** [comment]
Thank you @bartelink !

@cboudereau Do not you want to create PR that improve build process?

**Comment by cboudereau** [comment]
Yes the v1.1 nuget works nicely!

Sure, I am improving the build process.

Thanks!

**Comment by mchaloupka** [comment]
The support is already in build, see the yaml file (there is already a version).
https://github.com/fsprojects/TickSpec/blob/master/appveyor.yml

Optionally we can use some tool to increase the version automatically but I believe that this is enough for now (just increase the version there).

**Comment by bartelink** [comment]
Doh, thanks @mchaloupka (I'd never clicked thru until last night; hadn't realized it could literally have been two clicks to release the NuGet...)
Someone want to talk me out of fixing and force-pushing the version in the same commit ?

**Comment by mchaloupka** [comment]
It does not make sense to re-release the nuget. So, just commit the version increase. The force push will mean that you will have a release of non-existent commit. That is not nice.

I still plan different feature for next release - fixing how the tags are parsed and processed. There are several issues. However, I have not yet finished it for all cases. The parser is quite complicated.

**Comment by bartelink** [comment]
Did the force push; you make a very good point; I'll fix it up as a separate commit. Looking forward to seeing your next work!

**Comment by bartelink** [comment]
Closing this ticket for now; any and all build improvements are welcome ;)

**Comment by cboudereau** [comment]
@sergey-tihon : I have done the build improvement on this pull request : #15 with fake + paket and now all manual the procelain and plumbing are done by the fake build script.
