### ISSUE TITLE
Fix multiple scenarios with same name

### ISSUE THREAD

**Issue by mchaloupka** [fsprojects/TickSpec#26]
_Originally posted by @michalkovy in https://github.com/_render_node/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMTM3MDEwNjUwOnYy/pull_request_review_threads/discussion_

**Comment by michalkovy** [comment]
@mchaloupka did #27 fixed this issue fully? So, can we close it?

**Comment by mchaloupka** [comment]
Correct, already fixed.
