### ISSUE TITLE
2.0 Release for nuget

### ISSUE THREAD

**Issue by OnurGumus** [fsprojects/TickSpec#38]
I think it is a good idea to publish an official 2.0 release for nuget

**Comment by mchaloupka** [comment]
I definitely agree. I have just published a pull request with some minor build fixes and after it gets merged I will publish an official 2.0 release to nuget.

**Comment by mchaloupka** [comment]
The v2.0 has been released: https://www.nuget.org/packages/TickSpec/2.0.0
