### ISSUE TITLE
Documentation missing step for setup

### ISSUE THREAD

**Issue by rallentan** [fsprojects/TickSpec#41]
After installing the Nuget package, pressing 'F5' video doesn't run the tests as suggested in the documentation video (you can't run a class library). There must be some step not mentioned in the documentation needed to complete setup of TickSpec.

Steps to Replicate:
1. Create an F# xUnit test project in Visual Studio 2019
2. Add Feature.txt and StepDefinitions.fs files
3. Install TickSpec.xUnit
4. Press F5

Result: Error message box saying "A project with an Output Type of Class Library cannot be started directly [...]"

TickSpec seems to work a bit different from SpecFlow. What is the best way to run a TickSpec test from Visual Studio?

**Comment by bartelink** [comment]
The `TickSpec.xUnit` package is designed to expose the tests to the xUnit runner (well, the xUnit discoverer)

The general process whereby this works (and/or can go wrong) is covered in [this article from the xunit project](https://xunit.net/docs/getting-started/netfx/visual-studio#run-tests-visualstudio)

**Comment by rallentan** [comment]
Thank you. The example projects were also helpful in getting it setup (https://github.com/fsprojects/TickSpec/tree/master/Examples/ByFramework). It might be useful in the main documentation to reference these resources to get TickSpec setup with as little effort as possible.

**Comment by bartelink** [comment]
@rallentan That's a good suggestion... if you can find a nice place to put it in a PR, exactly where you would have benefited from it, it'd be really appreciated

**Comment by bartelink** [comment]
@rallentan Anything else you'd add to @cbouderau's PR ?
