### ISSUE TITLE
Newlines are removed from doc strings

### ISSUE THREAD

**Issue by deyanp** [fsprojects/TickSpec#60]
It seems Tickspec is filtering out all empty lines in a [doc string](https://relishapp.com/cucumber/cucumber/docs/gherkin/doc-strings), e.g. 

```
...
Then the generated file has the following content
"""
line1

line3

line5

"""
```

The resulting argument passed to the Then step looks like 

```
line1
line3
line5
```

Can you pls confirm this is a bug in TickSpec (Gherkin seems to preserve newlines in doc strings) ?

**Comment by bartelink** [comment]
Can't think of a good reason to strip them; perhaps the original intent was to strip ones at top and tail? (Can't think of a particularly good reason for that either)

**Comment by mchaloupka** [comment]
The original idea was to remove all empty lines to simplify parsing. I don't think that there was no intention to remove empty lines from doc strings.

Created pull requests: https://github.com/fsprojects/TickSpec/pull/62
